bind_addr = ":8080"
log_level = "debug"
database_url = "host=localhost dbname=restapi_dev sslmode=disable"
session_key="6GMWCUoXzu0IXUT3PlC?ZBe/xb0jyWh90AWgIA2aN/xfT3-t2nvZpWVy/Y9kiuFRSfHAAh4Cib?dcsPSkkwS-dQCe4vLfzX54mclRPAhF9h!fV3h1pysY7V!ifyU!bFAIAUpXeTuA=dL8blzobppPmHaf/3Iql!Gycwh9N-1!AfCCWhZCK0YsXoIPLvQ?mqLRZ62l8njTAbjyrlVEA5D/X3w-IZAEWksWsVlQ4wJa0M1az94WO8/LV7WzPB2uSGe"